export type Recommendation = {
  id: string;
  title: string;
  description: string;
  type: "content" | "technical" | "authority" | "citation";
  impact: number; // 1-100
  priority: "high" | "medium" | "low";
  status: "pending" | "in_progress" | "completed" | "archived";
  effort: "low" | "medium" | "high";
};

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  { id: "rec_1", title: "Create Comparison Landing Page", description: "Build a 'Our Brand vs Competitor' page to capture high-intent AI queries comparing you to top rivals.", type: "content", impact: 92, priority: "high", status: "pending", effort: "medium" },
  { id: "rec_2", title: "Expand FAQ Schema", description: "Implement extensive FAQ schema targeting long-tail questions generated by AI platforms in your niche.", type: "technical", impact: 85, priority: "high", status: "pending", effort: "low" },
  { id: "rec_3", title: "Build Industry Glossary", description: "Create an authoritative glossary of industry terms to feed LLM definitions and improve topical authority.", type: "content", impact: 78, priority: "medium", status: "pending", effort: "high" },
  { id: "rec_4", title: "Improve Third-Party Citations", description: "Secure mentions on top review sites (G2, Capterra) as LLMs heavily weight these for brand sentiment.", type: "citation", impact: 88, priority: "high", status: "in_progress", effort: "high" },
  { id: "rec_5", title: "Optimize Structured Data", description: "Ensure Organization and Product structured data are perfectly formatted to help AI agents parse your catalog.", type: "technical", impact: 70, priority: "medium", status: "completed", effort: "medium" },
  { id: "rec_6", title: "Publish Original Research", description: "Publish data-driven industry benchmarks. LLMs prefer linking to primary data sources over secondary content.", type: "authority", impact: 95, priority: "high", status: "pending", effort: "high" },
  { id: "rec_7", title: "Enhance Trust Signals", description: "Add clear contact info, author bios, and security badges to the footer across the entire site.", type: "authority", impact: 65, priority: "low", status: "pending", effort: "low" },
];

export const MOCK_GAP_ANALYSIS = [
  { topic: "API Documentation", userScore: 45, competitorScore: 88, gap: -43, priority: "high" },
  { topic: "Pricing Transparency", userScore: 90, competitorScore: 65, gap: 25, priority: "low" },
  { topic: "Integration Ecosystem", userScore: 30, competitorScore: 85, gap: -55, priority: "high" },
  { topic: "Enterprise Security", userScore: 75, competitorScore: 92, gap: -17, priority: "medium" },
  { topic: "Customer Success Stories", userScore: 50, competitorScore: 78, gap: -28, priority: "medium" },
];

export const MOCK_CONTENT_OPPORTUNITIES = [
  { id: "co_1", title: "Top 10 CRM Software of 2026", searchVolume: 12500, keywordDifficulty: 85, type: "listicle" },
  { id: "co_2", title: "CRM Buyer's Guide: What to Look For", searchVolume: 8200, keywordDifficulty: 65, type: "guide" },
  { id: "co_3", title: "Salesforce vs HubSpot vs Acme: Ultimate Comparison", searchVolume: 18000, keywordDifficulty: 72, type: "comparison" },
  { id: "co_4", title: "How AI is Changing Customer Relationship Management", searchVolume: 5400, keywordDifficulty: 45, type: "thought_leadership" },
  { id: "co_5", title: "CRM Implementation Checklist for Enterprise", searchVolume: 3200, keywordDifficulty: 50, type: "resource" },
];

export const MOCK_TIMELINE_GROWTH = [
  { month: "Month 1", visibility: 22, sentiment: 45, citations: 120 },
  { month: "Month 2", visibility: 35, sentiment: 52, citations: 280 },
  { month: "Month 3", visibility: 48, sentiment: 60, citations: 450 },
  { month: "Month 4", visibility: 61, sentiment: 68, citations: 610 },
  { month: "Month 5", visibility: 72, sentiment: 75, citations: 890 },
  { month: "Month 6", visibility: 88, sentiment: 84, citations: 1250 },
];

export const MOCK_ADMIN_CUSTOMERS = [
  { id: "cust_1", name: "Stripe", website: "stripe.com", plan: "enterprise", mrr: 2500, analysisCompleted: true, visibilityScore: 92, churnRisk: "low" },
  { id: "cust_2", name: "Notion", website: "notion.so", plan: "business", mrr: 999, analysisCompleted: true, visibilityScore: 85, churnRisk: "low" },
  { id: "cust_3", name: "Linear", website: "linear.app", plan: "growth", mrr: 299, analysisCompleted: true, visibilityScore: 74, churnRisk: "medium" },
  { id: "cust_4", name: "ClickUp", website: "clickup.com", plan: "business", mrr: 999, analysisCompleted: true, visibilityScore: 81, churnRisk: "low" },
  { id: "cust_5", name: "Figma", website: "figma.com", plan: "enterprise", mrr: 2500, analysisCompleted: true, visibilityScore: 95, churnRisk: "low" },
  { id: "cust_6", name: "Vercel", website: "vercel.com", plan: "starter", mrr: 99, analysisCompleted: true, visibilityScore: 68, churnRisk: "high" },
  { id: "cust_7", name: "Acme Corp", website: "acmecorp.com", plan: "free", mrr: 0, analysisCompleted: false, visibilityScore: 0, churnRisk: "high" },
];

export const LIMITED_REPORT = {
  visibilityScore: 24,
  brandAuthority: 38,
  contentStrength: 45,
  citationScore: 18,
  seoHealth: 72,
  trustScore: 41,
  topicCoverage: 33,
};
