"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { motion, AnimatePresence } from "framer-motion"
import { ChevronDown, Search } from "lucide-react"
import { SectionLabel } from "./primitives/SectionLabel"

interface FaqSegment {
  text: string
  href?: string
}

interface FaqItem {
  q: string
  a: FaqSegment[]
}

const FAQS: FaqItem[] = [
  {
    q: "What is AI search optimization?",
    a: [
      { text: "The practice of improving how a brand appears in answers generated by AI search engines and assistants. It covers earning citations, correcting inaccurate mentions, increasing " },
      { text: "Share of Voice", href: "/features/share-of-voice" },
      { text: ", and structuring content so AI engines can reference it reliably." },
    ],
  },
  {
    q: "What is an AI visibility platform?",
    a: [
      { text: "An AI visibility platform monitors how AI engines mention, cite, and describe brands, then measures that presence over time." },
    ],
  },
  {
    q: "How is Generative Engine Optimization different from traditional SEO?",
    a: [
      { text: "Traditional SEO targets ranking positions in search results pages. " },
      { text: "Generative Engine Optimization", href: "/generative-engine-optimization" },
      { text: " (GEO) targets presence inside AI-generated answers instead." },
    ],
  },
  {
    q: "What does Answer Engine Optimization involve?",
    a: [
      { text: "Answer Engine Optimization", href: "/answer-engine-optimization" },
      { text: " (AEO) means structuring content so answer engines can extract and reference it directly: clear definitions, direct answers to real questions, logical heading hierarchy, and entity-rich language." },
    ],
  },
  {
    q: "Which AI engines does Citationly cover?",
    a: [
      { text: "ChatGPT, Google Gemini, Claude, Perplexity, Microsoft Copilot, and Grok." },
    ],
  },
  {
    q: "How does the free analysis work?",
    a: [
      { text: "It scans the major AI engines for your brand and returns an initial snapshot of your mentions, citations, and " },
      { text: "Share of Voice", href: "/features/share-of-voice" },
      { text: " against key competitors. It requires only your brand details and takes minutes." },
    ],
  },
  {
    q: "Can Citationly replace my existing AI SEO or SEO tools?",
    a: [
      { text: "Citationly measures the AI answer layer that traditional SEO platforms do not cover, so most teams run it alongside their existing stack." },
    ],
  },
  {
    q: "Who inside a company uses Citationly?",
    a: [
      { text: "SEO managers and content teams use citation tracking and recommendations daily. Marketing directors and CMOs rely on " },
      { text: "Share of Voice", href: "/features/share-of-voice" },
      { text: " and competitor dashboards. Agencies use multi-brand monitoring." },
    ],
  },
]

function faqSearchText(item: FaqItem) {
  return `${item.q} ${item.a.map((s) => s.text).join("")}`.toLowerCase()
}

function FaqAnswer({ segments }: { segments: FaqSegment[] }) {
  return (
    <>
      {segments.map((seg, i) =>
        seg.href ? (
          <Link key={i} href={seg.href} className="text-primary underline underline-offset-2 hover:text-primary/80">
            {seg.text}
          </Link>
        ) : (
          <span key={i}>{seg.text}</span>
        )
      )}
    </>
  )
}

export function FaqSection() {
  const [query, setQuery] = useState("")
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const filtered = useMemo(() => {
    if (!query.trim()) return FAQS
    const q = query.toLowerCase()
    return FAQS.filter((f) => faqSearchText(f).includes(q))
  }, [query])

  return (
    <section className="relative py-32 bg-background">
      <div className="container mx-auto px-6 max-w-2xl">
        <div className="text-center mb-12">
          <div className="flex justify-center">
            <SectionLabel dark={false}>FAQ</SectionLabel>
          </div>
          <h2 className="text-4xl md:text-5xl font-semibold tracking-tight text-foreground">Questions, answered.</h2>
        </div>

        <div className="relative mb-8">
          <Search className="w-4 h-4 absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search questions..."
            className="w-full h-12 pl-11 pr-4 rounded-full border border-border bg-card text-sm outline-none focus:border-primary/40 transition-colors"
          />
        </div>

        <div className="flex flex-col gap-3">
          {filtered.map((faq, i) => {
            const isOpen = openIndex === i
            return (
              <div key={faq.q} className="rounded-2xl border border-border bg-card overflow-hidden">
                <button
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left"
                >
                  <span className="text-[15px] font-medium text-foreground">{faq.q}</span>
                  <motion.span animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.25 }}>
                    <ChevronDown className="w-4.5 h-4.5 text-muted-foreground shrink-0" />
                  </motion.span>
                </button>
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      className="overflow-hidden"
                    >
                      <p className="px-6 pb-5 text-[14px] text-muted-foreground leading-relaxed">
                        <FaqAnswer segments={faq.a} />
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            )
          })}
          {filtered.length === 0 && (
            <p className="text-center text-sm text-muted-foreground py-10">No questions match &quot;{query}&quot;.</p>
          )}
        </div>
      </div>
    </section>
  )
}
