import { Navbar } from "@/components/layouts/Navbar"
import { Footer } from "@/components/layouts/Footer"
import { SmoothScroll } from "@/components/features/landing/primitives/SmoothScroll"
import { Hero } from "@/components/features/landing/Hero"
import { SocialProof } from "@/components/features/landing/SocialProof"
import { HowItWorks } from "@/components/features/landing/HowItWorks"
import { ProductShowcase } from "@/components/features/landing/ProductShowcase"
import { PlatformWall } from "@/components/features/landing/PlatformWall"
import { FeatureShowcase } from "@/components/features/landing/FeatureShowcase"
import { ComparisonSection } from "@/components/features/landing/ComparisonTable"
import { UseCases } from "@/components/features/landing/UseCases"
import { Testimonials } from "@/components/features/landing/Testimonials"
import { Pricing } from "@/components/features/landing/Pricing"
import { FaqSection } from "@/components/features/landing/Faq"
import { FinalCta } from "@/components/features/landing/FinalCta"
import Script from "next/script"

export default function Home() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "name": "Citationly.ai",
        "url": "https://citationly.ai/",
        "logo": "https://citationly.ai/images/logo-dark.png",
        "contactPoint": [
          {
            "@type": "ContactPoint",
            "telephone": "+91 8668521368",
            "contactType": "customer service",
            "contactOption": ["TollFree", "HearingImpairedSupported"],
            "areaServed": "IN",
            "availableLanguage": "en"
          },
          {
            "@type": "ContactPoint",
            "telephone": "+91 8446425690",
            "contactType": "sales",
            "contactOption": ["TollFree", "HearingImpairedSupported"],
            "areaServed": "IN",
            "availableLanguage": "en"
          }
        ],
        "sameAs": [
          "https://www.facebook.com/profile.php?id=61591659194700",
          "https://www.linkedin.com/company/citationly/",
          "https://www.instagram.com/citationly.ai/"
        ]
      },
      {
        "@type": "Product",
        "name": "Citationly AI Visibility Intelligence Platform",
        "description": "Enterprise platform for measuring, monitoring, and improving how AI platforms discover, understand, recommend, and cite your brand.",
        "brand": {
          "@type": "Brand",
          "name": "Citationly"
        },
        "offers": {
          "@type": "Offer",
          "priceCurrency": "USD",
          "price": "299.00"
        }
      },
      {
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://citationly.ai/" },
          { "@type": "ListItem", "position": 2, "name": "About", "item": "https://citationly.ai/about" },
          { "@type": "ListItem", "position": 3, "name": "Features", "item": "https://citationly.ai/features" },
          { "@type": "ListItem", "position": 4, "name": "Blog", "item": "https://citationly.ai/blog" },
          { "@type": "ListItem", "position": 5, "name": "Pricing", "item": "https://citationly.ai/pricing" },
          { "@type": "ListItem", "position": 6, "name": "Contact", "item": "https://citationly.ai/contact" }
        ]
      },
      {
        "@type": "FAQPage",
        "mainEntity": [
          {
            "@type": "Question",
            "name": "What is AI search optimization?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "AI search optimization is the practice of improving how a brand appears in answers generated by AI search engines and assistants. It covers earning citations, correcting inaccurate mentions, increasing Share of Voice, and structuring content so AI engines can reference it reliably."
            }
          },
          {
            "@type": "Question",
            "name": "What is an AI visibility platform?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "An AI visibility platform monitors how AI engines mention, cite, and describe brands, then measures that presence over time. Citationly extends visibility measurement with competitor benchmarking and optimization recommendations, making it a full AI Search Intelligence Platform."
            }
          },
          {
            "@type": "Question",
            "name": "How is Generative Engine Optimization different from traditional SEO?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "Traditional SEO targets ranking positions in search results pages. Generative Engine Optimization targets presence inside AI-generated answers, where engines synthesize responses from selected sources. The two share foundations, but GEO requires measuring citations and mentions rather than rankings and clicks."
            }
          },
          {
            "@type": "Question",
            "name": "What does Answer Engine Optimization involve?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "Answer Engine Optimization structures content so answer engines can extract and reference it directly. In practice this means clear definitions, direct answers to real questions, logical heading hierarchy, and entity-rich language that engines can parse confidently."
            }
          },
          {
            "@type": "Question",
            "name": "Which AI engines does Citationly cover?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "Citationly monitors ChatGPT, Google Gemini, Claude, Perplexity, Microsoft Copilot, and Grok. Engine coverage expands as new assistants reach meaningful usage in enterprise buying research."
            }
          },
          {
            "@type": "Question",
            "name": "How does the free analysis work?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "The free analysis scans the major AI engines for your brand and returns an initial snapshot of your mentions, citations, and Share of Voice against key competitors. It requires only your brand details and takes minutes to set up."
            }
          },
          {
            "@type": "Question",
            "name": "Can Citationly replace my existing AI SEO or SEO tools?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "Citationly measures the AI answer layer that traditional SEO platforms do not cover, so most teams run it alongside their existing stack. Your rank trackers keep covering classic search while Citationly covers AI engines."
            }
          },
          {
            "@type": "Question",
            "name": "Who inside a company uses Citationly?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "SEO managers and content teams use citation tracking and recommendations daily. Marketing directors and CMOs rely on Share of Voice and competitor dashboards for strategy and reporting. Agencies use multi-brand monitoring to deliver AI visibility services to clients."
            }
          }
        ]
      }
    ]
  }

  return (
    <>
      <Script
        id="schema-jsonld"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <SmoothScroll>
        <main className="min-h-screen relative selection:bg-primary/30">
          <Navbar heroVariant="dark" />
          <Hero />
          <SocialProof />
          <HowItWorks />
          <ProductShowcase />
          <PlatformWall />
          <FeatureShowcase />
          <ComparisonSection />
          <UseCases />
          <Testimonials />
          <Pricing />
          <FaqSection />
          <FinalCta />
          <Footer />
        </main>
      </SmoothScroll>
    </>
  )
}
