export default function ReportFooter() {
  const currentYear = new Date().getFullYear()
  return (
    <footer className="max-w-7xl mx-auto px-6 mt-16 pt-8 border-t border-slate-200">
      <div className="flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-slate-500">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded bg-blue-600 flex items-center justify-center opacity-80">
            <span className="font-bold text-white text-xs leading-none">O</span>
          </div>
          <span className="font-medium text-slate-700">Citationly</span>
        </div>
        
        <p>© {currentYear} Citationly. All rights reserved. Generated by the AI Engine.</p>
        
        <div className="flex items-center gap-4">
          <a href="#" className="hover:text-slate-800 transition-colors">Methodology</a>
          <a href="#" className="hover:text-slate-800 transition-colors">Support</a>
        </div>
      </div>
    </footer>
  )
}
